#! /usr/bin/env python
'''Deployment script for standard DEEPi

'''

import logging, sys
from datetime import datetime
from pathlib import Path

from deepi import load_camera
from deepi import VideoRecorder, SocketStreamer, StillCamera
from deepi import RecorderThread
from deepi import DEEPiConfig
from deepi import WebSocketStream

from deepi import PWMLightController as LightController

# Config
logging.debug("Reading config file")
config = DEEPiConfig('deepi.conf')

# Logging
log_path  = Path(config.get('ALL', 'logpath'))
log_path.mkdir(parents=True, exist_ok=True)
log_file  = (log_path / datetime.utcnow().strftime('%Y%m%dT%H%M%S')).with_suffix('.txt')

# Make sure other folders exist
for sec in ['STILLCAM', 'RECORDER']:
    save_path  = Path(config.get(sec, 'outpath'))
    save_path.mkdir(parents=True, exist_ok=True)

config_log_level = config.get('ALL', 'loglevel').upper()
if config_log_level=='CRITICAL':
    log_level = logging.CRITICAL
elif config_log_level=='ERROR':
    log_level = logging.ERROR
elif config_log_level=='WARNING':
    log_level = logging.WARNING
elif config_log_level=='INFO':
    log_level = logging.INFO
elif config_log_level=='DEBUG':
    log_level = logging.DEBUG
elif config_log_level=='NOTSET':
    log_level = logging.NOTSET
else:
    logging.warning("log level does not match")

logging.root.handlers = []
logging.basicConfig(format="%(asctime)s [%(levelname)s] %(message)s",
                    level=log_level,
                    handlers=[
                        logging.FileHandler(log_file),
                        logging.StreamHandler(sys.stdout)
                    ]
                    )


# Set up camera
logging.info('Initializing camera')
picam = load_camera(config)

logging.info("Setting up video recorder")
recorder = VideoRecorder(picam, 
                         splitter_port=config.getint('RECORDER','splitter'),
                         outpath=config.get('RECORDER','outpath'),
                         )

logging.info("Setting up still camera")
camera = StillCamera(picam, 
                     splitter_port=config.getint('STILLCAM','splitter'), 
                     outpath=config.get('STILLCAM','outpath')
                     )

if config.getboolean('STREAM','streaming'):
    streamer = make_web_streamer(picam, config)

# Lights
logging.debug("Starting lights")
pin_num = config.getint('LIGHTS', 'gpio')
lights = LightController(pin_num)

# Generate app
if config.getboolean('WEBAPP','webapp'):
    app = make_app(stillcam, recorder, streamer, lights)
    app.run(host='0.0.0.0',port=5000,debug=False)
