#!/bin/env python3

from picamera import PiCamera

# Initialize camera
picam = PiCamera( resolution=(1920,1080),
                  framerate=30
)
sleep(2)                # wait for camera to wake up

